name: Android Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget tar unzip lib32stdc++6 lib32z1

    - name: Set up Android SDK
      run: |
        export ANDROID_HOME="${HOME}/android-home"
        mkdir -p $ANDROID_HOME
        wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${{ env.ANDROID_SDK_TOOLS }}_latest.zip
        pushd $ANDROID_HOME
        unzip -d cmdline-tools cmdline-tools.zip
        popd
        export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/tools/bin/
        sdkmanager --version

        echo "y" | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
        sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${{ env.ANDROID_COMPILE_SDK }}"
        sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
        sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"

    - name: Build and lint
      run: |
        chmod +x ./gradlew
        ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build release APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        body: "Created using GitHub Actions"
        draft: false
        prerelease: false

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/**/outputs/**/*.apk
